refactor(config): 迁移 Dice 中的设置项至独立的 struct 中
sealdice/sealdice-core pull request #1070
Opened 2024-10-16 18:14 UTC by JustAnotherID

~~打一波复活赛（~~

2024-10-17 01:26 UTC, Xiangze-Li requested changes
#509 仍存在

2024-10-17 02:02 UTC, Xiangze-Li commented on dice/dice.go
>  	d.loadAdvanced()
#509 中无法读取文件列表的原因：文件列表是在 注册插件 时读取，而加载配置时将文件列表覆盖成默认值 nil 了。

2024-10-17 02:03 UTC, Xiangze-Li commented
请考虑把目标分支改为 master，保持 1.4 分支尽可能稳定

2024-10-17 08:56 UTC, JustAnotherID commented on dice/dice.go
>  	d.loadAdvanced()
自定义回复失效的问题已解决

2024-10-19 12:21 UTC, Xiangze-Li approved these changes
I see no bad

2024-10-19 12:21 UTC, merged