feat: Slack Adapter
sealdice/sealdice-core pull request #400
Opened 2023-11-11 09:24 UTC by Szzrain

@FlameTEXT 实现的大部分功能，我将此分支rebase并修复build错误后提交此pr

2023-11-12 22:53 UTC, Szzrain commented
有点寄，不太清楚slack api怎么用的，先拖一段时间

2023-11-16 05:57 UTC, Xiangze-Li requested changes

2023-11-16 05:57 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +			return
记录日志

2023-11-16 05:57 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +		log.Error("连接失败：", event.Data)
日志内容中增加平台名 Slack 和账号信息, 形如

> Slack 账号 \<UserID\> 连接失败: err

2023-11-16 05:57 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +		log.Error("连接失败：", event.Data)
下面 连接断开 同理

2023-11-16 05:57 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +func (pa *PlatformAdapterSlack) SendFileToPerson(ctx *MsgContext, uid string, path string, flag string) {
留日志或发送一条「不支持」的消息

(style) 不使用的实参改成下划线

2023-11-16 05:57 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +func (pa *PlatformAdapterSlack) SendFileToPerson(ctx *MsgContext, uid string, path string, flag string) {
下面几个类似

2023-11-16 05:57 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +	if u, e := pa.userCache.Load(user); e {
使用有意义的变量名. `e` 既可以是 `exist` 也可以是 `error`

2023-11-16 06:26 UTC, Szzrain commented on dice/platform_adapter_slack.go
> +		log.Error("连接失败：", event.Data)
> 日志内容中增加平台名 Slack 和账号信息, 形如
> 
> > Slack 账号 <UserID> 连接失败: err

不可行，此时 UserID 极有可能为空字符串

2023-11-16 06:30 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +		log.Error("连接失败：", event.Data)
为空串也可以接受, 日志里的内容尽力而为即可

2023-11-16 06:33 UTC, Xiangze-Li commented on dice/platform_adapter_slack.go
> +		log.Error("连接失败：", event.Data)
marked as resolved

2023-11-16 06:43 UTC, JustAnotherID approved these changes
LGTM

2023-11-16 06:47 UTC, merged