feat: 群组刷屏警告
sealdice/sealdice-core pull request #406
Opened 2023-11-15 15:23 UTC by Verplitic

增加了群组内许多人刷屏时发送警告，并增加群组怒气值。个人刷屏优先于群组刷屏。

修改了原本的一些字段（添加了迁移代码），增加了自定义群组刷屏速率的设置项。

sealdice-ui https://github.com/sealdice/sealdice-ui/pull/93

2023-11-15 15:31 UTC, JustAnotherID requested changes

2023-11-15 15:31 UTC, JustAnotherID commented on api/dice_config.go
> +	PersonalReplenishRate   string   `json:"personalReplenishRate"` // 个人自定义速率
修改了设置项名的话，原来的设置考虑如何迁移？

2023-11-15 15:31 UTC, JustAnotherID commented on dice/im_session.go
> +					if s.Parent.RateLimitEnabled && msg.Platform == "QQ" {
这是把master的白名单去掉了？🤔

2023-11-15 15:31 UTC, JustAnotherID commented on dice/im_session.go
>  									ReplyToSender(mctx, msg, "您的指令频率过高，请注意。")
要不顺便把这抽出来作为自定义文案？

2023-11-15 15:31 UTC, JustAnotherID commented on dice/im_session.go
> +									ReplyToSender(mctx, msg, "该群组内指令频率过高，请注意。")
同上，抽出来作为自定义文案如何？

2023-11-15 15:34 UTC, JustAnotherID commented on api/dice_config.go
> +	PersonalReplenishRate   string   `json:"personalReplenishRate"` // 个人自定义速率
唔，在下面看见了迁移代码，但总觉得迁移代码和正式代码混杂在一起不太好

2023-11-15 16:24 UTC, Verplitic commented on dice/im_session.go
> +					if s.Parent.RateLimitEnabled && msg.Platform == "QQ" {
挪到832行了

2023-11-16 02:31 UTC, Xiangze-Li commented on dice/dice.go
> -	ImSession               *IMSession             `yaml:"imSession" jsbind:"imSession"`
考虑把你修改的部分拆出来加个空行？这样就不会造成这么多行diff了

2023-11-16 02:59 UTC, Verplitic commented on dice/dice.go
> -	ImSession               *IMSession             `yaml:"imSession" jsbind:"imSession"`
改了

2023-11-16 04:10 UTC, Xiangze-Li requested changes

2023-11-16 04:10 UTC, Xiangze-Li commented on api/dice_config.go
> +				myDice.PersonalBurst = 3
建议入参非法时不做修改, 否则可能造成修改结果完全背离操作预期

2023-11-16 04:10 UTC, Xiangze-Li commented on api/dice_config.go
> +				fmt.Printf("解析刷屏警告速率失败，恢复默认速率: %v\n", err)
同上(2) 建议入参非法时不做修改, 否则可能造成修改结果完全背离操作预期

2023-11-16 04:10 UTC, Xiangze-Li commented on api/dice_config.go
> +				myDice.GroupBurst = 3
同上(3) 建议入参非法时不做修改, 否则可能造成修改结果完全背离操作预期

2023-11-16 04:10 UTC, Xiangze-Li commented on api/dice_config.go
>  				fmt.Printf("解析刷屏警告速率失败，恢复默认速率: %v\n", err)
同上(4) 建议入参非法时不做修改, 否则可能造成修改结果完全背离操作预期

2023-11-16 05:43 UTC, Szzrain commented on api/dice_config.go
> +	PersonalReplenishRate   string   `json:"personalReplenishRate"` // 个人自定义速率
> 唔，在下面看见了迁移代码，但总觉得迁移代码和正式代码混杂在一起不太好

同意，最好能单独取出来一个 function 这样方便未来的移除

2023-11-16 06:49 UTC, Verplitic commented on api/dice_config.go
> +	PersonalReplenishRate   string   `json:"personalReplenishRate"` // 个人自定义速率
新建 migrate/v141_deprecated_config.go 用于迁移

2023-11-16 07:07 UTC, Xiangze-Li commented on api/dice_config.go
> +			if myDice.PersonalBurst >= 1 {
```go
if customBurst >= 1 {
```

2023-11-16 07:07 UTC, Xiangze-Li commented on api/dice_config.go
> +			if myDice.GroupBurst >= 1 {
```go
if customBurst >= 1
```

2023-11-16 09:14 UTC, closed without merging