feat(js): js 插件增加签名机制，支持打包内置插件到二进制
sealdice/sealdice-core pull request #433
Opened 2023-11-21 15:35 UTC by JustAnotherID

1. 增加js插件签名机制，校验插件首行 `// sign xxxxxx` 标识以识别是否是官方发布的插件；
2. 支持内置插件机制，允许打包进二进制，内置插件支持更新和卸载更新；
3. 增加自动化对文件签名的相关机制。

ui调整：sealdice/sealdice-ui#101

2023-11-21 16:16 UTC, Xiangze-Li requested changes

2023-11-21 16:16 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +		data := signRe.ReplaceAll(rawData, []byte(""))
签名的长度是固定的，不妨直接读rawData的前若干字节，判断是否为「// sign 」开头、后续一串字符串

2023-11-21 16:16 UTC, Xiangze-Li commented on dice/utils_rsa.go
> +package dice
做成 `utils/crypto` 包更合适

2023-11-21 16:16 UTC, Xiangze-Li commented on signature/gen/sign_mods.go
> +	err = os.WriteFile("[signed]"+name, newData, 0644)
似乎只有签名，没有把本体也加上？

2023-11-21 16:16 UTC, Xiangze-Li commented on static/scripts/seal_mod.public.pem
> +-----BEGIN PUBLIC KEY-----
虽然这个是公钥，但是我仍然觉得把他留到编译期再注入更好一些。

类似dev版本的version name那样。

2023-11-21 16:16 UTC, Xiangze-Li commented on dice/dice.go
> +	Official     bool     `yaml:"-" json:"-" jsbind:"official"` // 官方插件
是否有可能被从js侧修改？

2023-11-21 16:16 UTC, Xiangze-Li commented on dice/dice.go
> +	Source  *JsScriptInfo `yaml:"-" json:"-"`
是否有可能通过 extinfo 修改 source 中的 official 字段？

2023-11-21 16:16 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +	if len(matches) > 1 {
判断 `len(matches) == 0` 之后直接返回，不写 else 分支。大块逻辑可以减少一层缩进。

2023-11-21 16:18 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +	OfficialModPublicKey = ``
有此评论是因为我想把这个 pubkey 做成和 dev 版本号类似的做法，即，在编译命令中注入值。

2023-11-21 16:18 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +	Digest string `json:"digest"`
前端能显示是否官方就可以了，感觉无需显示具体的Hash

2023-11-21 17:44 UTC, fy0 commented on .github/workflows/build.yml
新增了一个目录……是否考虑将生成内容都收拢在一个目录，这样就不会越来越多？

2023-11-21 17:48 UTC, fy0 commented on dice/dice_jsvm.go
> +	OfficialModPublicKey = ``
公钥直接写成const在代码里是不是好点

2023-11-21 17:49 UTC, fy0 commented on dice/dice_jsvm.go
> +	signRe = regexp.MustCompile(`// sign\s+([^\r\n]+)?[\r\n]+`)
不用re可以节省微弱性能 不过没必要

2023-11-21 17:50 UTC, fy0 commented on dice/utils_rsa.go
> +package dice
+1

2023-11-21 17:51 UTC, fy0 commented on static/scripts/seal_mod.public.pem
> +-----BEGIN PUBLIC KEY-----
我就不一样了，我甚至觉得直接写入代码比较好……

2023-11-21 23:47 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +	signRe = regexp.MustCompile(`// sign\s+([^\r\n]+)?[\r\n]+`)
其一，直接截取前若干Bytes更符合「签名在文件头部」这一语义；截取之后如何判断格式就无所谓是否RE了。

其二，签名的长度相对于文件长度通常相当短。在存在签名的情况下，RE可以返回第一匹配，不会有后续开销；但是，如果不存在签名，RE就必须把整个文件内容扫描一遍，还是不够理想。

2023-11-21 23:50 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +	Digest string `json:"digest"`
看了一下 ui 的对应修改，并未使用这个字段。那么不妨直接 `json:"-"` 在前后端传递的数据里去掉这个字段

2023-11-22 01:37 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +	OfficialModPublicKey = ``
> 有此评论是因为我想把这个 pubkey 做成和 dev 版本号类似的做法，即，在编译命令中注入值。

公钥似乎没有编译注入的必要，我还是希望把公钥文件独立出来，不希望混入代码中

2023-11-22 01:38 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +	OfficialModPublicKey = ``
> 公钥直接写成const在代码里是不是好点

代码里会有一长串公钥，感觉不是很美观（

2023-11-22 01:40 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +	OfficialModPublicKey = ``
想到，这里不只是美观问题。如果公钥是独立文件，恶意骰主可以直接将其替换为自己的公钥，将自己签名的插件伪装成官方插件。

2023-11-22 02:08 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +	signRe = regexp.MustCompile(`// sign\s+([^\r\n]+)?[\r\n]+`)
签名结果的长度和密钥有关系，为了避免对替换密钥场景造成影响会改成截取第一行

2023-11-22 02:09 UTC, JustAnotherID commented on signature/gen/sign_mods.go
> +	err = os.WriteFile("[signed]"+name, newData, 0644)
怪，好像是修改的时候手滑把本体删了（

2023-11-22 02:10 UTC, JustAnotherID commented on dice/dice.go
> +	Source  *JsScriptInfo `yaml:"-" json:"-"`
不太确定，没有通过 jsbind 暴露出去应该不会有影响？

2023-11-22 02:12 UTC, JustAnotherID commented on .github/workflows/build.yml
目前好像就 `signature` 和 `static` 俩，先这样平铺，如果后面超过三个了再归拢呗

2023-11-22 02:21 UTC, Xiangze-Li commented on dice/dice.go
> +	Source  *JsScriptInfo `yaml:"-" json:"-"`
还是要验证一下, `JsScriptInfo` 结构的 `Official` 字段是暴露给 JS 了.

2023-11-22 02:21 UTC, Xiangze-Li commented on .github/workflows/build.yml
不要拉第一泡啊啊啊

2023-11-22 02:41 UTC, Szzrain commented on dice/dice.go
> +	Official     bool     `yaml:"-" json:"-" jsbind:"official"` // 官方插件
> 是否有可能被从js侧修改？

jsbind 的 变量有从 js 侧修改的可能，因此如果此变量会被用于关键性的逻辑判断则不应暴露。如果一定要提供 js 内获取此变量的方式我建议添加一个 `isOfficial()` 的函数

2023-11-22 03:29 UTC, JustAnotherID commented on dice/dice.go
> +	Official     bool     `yaml:"-" json:"-" jsbind:"official"` // 官方插件
先移除了这个字段的暴露

2023-11-22 03:30 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +	OfficialModPublicKey = ``
> 想到，这里不只是美观问题。如果公钥是独立文件，恶意骰主可以直接将其替换为自己的公钥，将自己签名的插件伪装成官方插件。
> 
> 因此公钥必须是一个编译后不能改变的值。

这个问题不存在的，因为最后公钥文件是打包进二进制的，只有在源码阶段才是文件形式。

2023-11-22 03:32 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +		data := signRe.ReplaceAll(rawData, []byte(""))
改为读取第一行了

2023-11-22 03:32 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +	Digest string `json:"digest"`
已去除

2023-11-22 03:33 UTC, JustAnotherID commented on dice/utils_rsa.go
> +package dice
已迁移

2023-11-22 03:33 UTC, JustAnotherID commented on static/scripts/seal_mod.public.pem
> +-----BEGIN PUBLIC KEY-----
同上，希望在源码阶段作为独立公钥文件方便测试时替换

2023-11-22 03:34 UTC, JustAnotherID commented on dice/dice.go
> +	Source  *JsScriptInfo `yaml:"-" json:"-"`
`JsScriptInfo` 结构的 `Official` 字段拿掉导出了

2023-11-22 03:45 UTC, Xiangze-Li approved these changes
I'm happy. 决定不修改的部分留下说明就可以 resolve 了.

2023-11-22 03:48 UTC, Xiangze-Li commented on signature/gen/sign_mods.go
> +	err = os.WriteFile("[signed]"+name, newData, 0644)
是否漏了此处的修正?

2023-11-22 03:52 UTC, JustAnotherID commented on .github/workflows/build.yml
目前决定就先平铺

2023-11-22 03:54 UTC, JustAnotherID commented on signature/gen/sign_mods.go
> +	err = os.WriteFile("[signed]"+name, newData, 0644)
`newData := []byte(fmt.Sprintf(signStrTmpl, sign) + string(data))`，没啥问题

2023-11-22 07:33 UTC, merged