feat(official-qq): 增加 qq 官方 bot 支持
sealdice/sealdice-core pull request #435
Opened 2023-11-22 18:00 UTC by JustAnotherID

ui调整：sealdice/sealdice-ui#103

2023-11-22 22:50 UTC, Xiangze-Li commented
`dice/dice_ban.go:165` 补充 type switch 的分支

2023-11-22 22:55 UTC, Szzrain commented
> `dice/dice_ban.go:165` 补充 type switch 的分支

没必要吧？

2023-11-22 22:59 UTC, Xiangze-Li commented
> > `dice/dice_ban.go:165` 补充 type switch 的分支
> 
> 没必要吧？

算是某种编程好习惯吧(

既然官方 API 是一种 QQ Adapter, 在涉及 QQ Adapter 的分支上就要覆盖到, 而不应该让它走 default.

2023-11-23 01:26 UTC, Szzrain requested changes

2023-11-23 01:26 UTC, Szzrain commented on dice/platform_adapter_official_qq.go
> +		select {
如无必要，此处不应阻塞，因为我看到调用 `Serve()` 的地方都需要其返回值以进行下一步操作

2023-11-23 01:26 UTC, Szzrain commented on dice/platform_adapter_official_qq.go
> +		_ = pa.SessionManager.Start(ws, token, &intent)
如果 `Start()` 还没有执行完毕是否会影响下面的 `pa.Api.Me()` 的调用？

2023-11-23 01:26 UTC, Szzrain commented on dice/platform_adapter_official_qq.go
> +			msg.Sender.Nickname = "未知"
留空是否更好些？

2023-11-23 03:37 UTC, JustAnotherID commented
> `dice/dice_ban.go:165` 补充 type switch 的分支

差点忘了，补上！

2023-11-23 03:38 UTC, JustAnotherID commented on dice/platform_adapter_official_qq.go
> +		select {
移除了好像没啥问题，想不起来当时为啥选择阻塞了（

2023-11-23 10:40 UTC, fy0 commented on dice/platform_adapter_official_qq.go
> +			msg.Sender.Nickname = "未知"
要不写“用户” / “玩家” 之类吧，或者让自定义？~~旅行者 / 博士~~

2023-11-23 10:47 UTC, Xiangze-Li commented on dice/platform_adapter_official_qq.go
> +			msg.Sender.Nickname = "未知"
之前群里聊了一下，结论是用 QQ 返回 ID 的最后四位拼成 `用户XXXX` 的样式

2023-11-23 12:08 UTC, Xiangze-Li commented on dice/platform_adapter_official_qq.go
> +			msg.Sender.Nickname = "用户" + msgQQ.Author.MemberOpenID[len(msgQQ.Author.MemberOpenID)-4:]
有没有上游错误导致 `MemberOpenID` 为空, 从而导致下标越界的可能性？

2023-11-23 12:09 UTC, JustAnotherID commented on dice/platform_adapter_official_qq.go
> +			msg.Sender.Nickname = "用户" + msgQQ.Author.MemberOpenID[len(msgQQ.Author.MemberOpenID)-4:]
MemberOpenID 是唯一键，这能为空没法做了吧（

2023-11-23 12:11 UTC, Xiangze-Li commented on dice/platform_adapter_official_qq.go
> +			msg.Sender.Nickname = "用户" + msgQQ.Author.MemberOpenID[len(msgQQ.Author.MemberOpenID)-4:]
上游错误嘛(

2023-11-23 22:48 UTC, Szzrain requested changes

2023-11-23 22:48 UTC, Szzrain commented on dice/platform_adapter_official_qq.go
> +				log.Error("official qq 启动失败")
这里如果报错了应当把错误信息也打印出来

2023-11-23 22:48 UTC, Szzrain commented on dice/platform_adapter_official_qq.go
> +		_ = pa.SessionManager.Start(ws, token, &intent)
同上，如果这里报错了也应当打印错误信息

2023-11-27 13:40 UTC, JustAnotherID commented on dice/platform_adapter_official_qq.go
> +				log.Error("official qq 启动失败")
处理了

2023-11-28 01:54 UTC, JustAnotherID commented on dice/platform_adapter_official_qq.go
> +		_ = pa.SessionManager.Start(ws, token, &intent)
处理了

2023-11-28 01:55 UTC, Xiangze-Li reviewed
一些写法优化建议

2023-11-28 01:55 UTC, Xiangze-Li commented on dice/im_session.go
> +		if ep.ProtocolType == "official" {
考虑用 switch 重构一下？

2023-11-28 02:00 UTC, Xiangze-Li commented on dice/platform_adapter_official_qq.go
> +	log.Debugf("收到文字频道消息：%v, %v", event, data)
以及私聊消息的那里

2023-11-28 08:58 UTC, Szzrain submitted a review, later dismissed
刚刚被打回，需要接入私聊与频道，否则无法过tx审核

2023-11-28 09:00 UTC, Szzrain commented
> 刚刚被打回，需要接入私聊与频道，否则无法过tx审核

我尝试过后频道中与私聊均无反应，不知道是哪里的问题

2023-11-28 10:15 UTC, JustAnotherID commented on dice/im_session.go
> +		if ep.ProtocolType == "official" {
已调整

2023-11-28 10:16 UTC, JustAnotherID commented on dice/platform_adapter_official_qq.go
> +	log.Debug("official qq server")
选择保留这些debug日志

2023-11-28 10:18 UTC, JustAnotherID commented on dice/platform_adapter_official_qq.go
> +			pa.Session.Parent.Logger.Warn("official qq 群聊消息暂不支持发送 @，跳过该部分")
已调整

2023-11-28 10:22 UTC, Xiangze-Li reviewed
I'm happy, 看 Szz 实测效果合并吧?

2023-11-28 10:44 UTC, Xiangze-Li approved these changes
LGTM

2023-11-28 10:46 UTC, merged