refactor(config): 迁移 `Dice` 中的设置项至独立的 struct 中
sealdice/sealdice-core pull request #465
Opened 2023-12-04 14:20 UTC by JustAnotherID

2023-12-04 15:13 UTC, fy0 commented
呃啊 巨大改动

2023-12-04 15:45 UTC, JustAnotherID commented
> 呃啊 巨大改动 感觉急需1.5branch

不急，可以先等 1.4.2 发布之后在合并

2023-12-05 01:28 UTC, Xiangze-Li requested changes

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +var DefaultConfig = Config{
建议
1. 默认配置单独放一个文件，可以减小每个文件的行数
2. 写明字段名
3. 子结构以零值为默认值的，也写字段，保持所有字段完整

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +				fmt.Printf("解析PersonalReplenishRate失败: %v", errParse)
这个时候已经有 dice 了，或许可以打到 dice.Logger 去？

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +			fmt.Printf("进行配置文件版本升级: %d -> %d", c.VersionCode, 10003)
不统一的输出

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +			c.CustomReplyConfigEnable = false
被下文覆盖的逻辑，参考166行

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +	if c.ConfigVersion == 0 {
`c.ConfigVersion == 0` 的分支进入逻辑和 `c.ConfigVersion = ConfigVersion` 的赋值逻辑，是否会造成下文依据版本号判断写默认值的逻辑无效？

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +	} else {
好习惯：if 和 else 对调，短分支直接 return 后长分支可以减一级缩进

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice_config.go
> +	IsDeckLoading           bool           `yaml:"-" json:"-"`                                             // 正在加载中
这种不会落盘的字段是临时性质，感觉就放在 `Dice` 类里也是合理的

2023-12-05 01:28 UTC, Xiangze-Li commented on dice/dice.go
> +type RootConfig struct { //nolint:revive
nolint 标签可以去掉了。在这里添加 nolint 的原因是 revive 规则禁止符号名 DiceConfig 出现在 dice 包中（dice 重复）

2023-12-05 01:31 UTC, Xiangze-Li commented on dice/dice_config.go
> +var DefaultConfig = Config{
另外：加载配置需要默认值时，从这个对象取，而不是再写一遍。这是维护一个完整的默认配置对象的意义所在。

2023-12-05 02:39 UTC, JustAnotherID commented on dice/dice_config.go
> +	if c.ConfigVersion == 0 {
下文判断的是旧的版本号字段 `VersionCode`，此处使用新的 `ConfigVersion`，想法是未来弃用旧 `VersionCode`，仅在没有新版本号（即为0）时迁移一次。

2023-12-05 02:54 UTC, JustAnotherID commented on dice/dice_config.go
> +var DefaultConfig = Config{
已调整，下面取默认值的代码也修改为取 `DefaultConfig` 了

2023-12-05 02:54 UTC, JustAnotherID commented on dice/dice_config.go
> +				fmt.Printf("解析PersonalReplenishRate失败: %v", errParse)
已修改

2023-12-05 02:55 UTC, JustAnotherID commented on dice/dice_config.go
> +			fmt.Printf("进行配置文件版本升级: %d -> %d", c.VersionCode, 10003)
这段log似乎没有必要，先移除了

2023-12-05 02:55 UTC, JustAnotherID commented on dice/dice_config.go
> +	} else {
已调整

2023-12-05 02:55 UTC, JustAnotherID commented on dice/dice_config.go
> +			c.CustomReplyConfigEnable = false
同下

2023-12-05 02:57 UTC, JustAnotherID commented on dice/dice_config.go
> +			c.CustomReplyConfigEnable = false
已调整

2023-12-05 02:57 UTC, Xiangze-Li commented on dice/dice_config.go
> +	if c.ConfigVersion == 0 {
哦哦，明白了

2023-12-05 02:59 UTC, JustAnotherID commented on dice/dice_config.go
> +	IsDeckLoading           bool           `yaml:"-" json:"-"`                                             // 正在加载中
这个本来是打算和 `DeckList` 一起迁移过来方便统一管理的，但是 `DeckList` 由于被导出到 js 中了目前不能动，这个字段已经改回 `Dice` 中了。

2023-12-05 02:59 UTC, JustAnotherID commented on dice/dice.go
> +type RootConfig struct { //nolint:revive
已处理

2023-12-05 03:09 UTC, Xiangze-Li requested changes
还有两个漏了的硬编码默认值，或许刷屏限制那边也有没发现的（可能会和步棋那边冲突）

功能测试过是OK的？

2023-12-05 03:09 UTC, Xiangze-Li commented on dice/dice_manager.go
> +		defaultDice.Config.MessageDelayRangeStart = 0.4
硬编码的默认值

2023-12-05 03:09 UTC, Xiangze-Li commented on dice/ext_log.go
> +					ctx.Dice.Config.LogSizeNoticeCount = 500
硬编码的默认值

2023-12-05 03:30 UTC, Xiangze-Li commented
> 还有两个漏了的硬编码默认值，或许刷屏限制那边也有没发现的（可能会和步棋那边冲突）
> 
> 功能测试过是OK的？

步棋那边新增（重构）了几个硬编码默认值，你或许需要rebase master之后重新调整一下

2023-12-05 05:02 UTC, JustAnotherID commented on dice/dice_manager.go
> +		defaultDice.Config.MessageDelayRangeStart = 0.4
已调整

2023-12-05 05:02 UTC, JustAnotherID commented on dice/ext_log.go
> +					ctx.Dice.Config.LogSizeNoticeCount = 500
已调整

2023-12-05 05:03 UTC, JustAnotherID commented
> > 还有两个漏了的硬编码默认值，或许刷屏限制那边也有没发现的（可能会和步棋那边冲突）
> > 功能测试过是OK的？
> 
> 步棋那边新增（重构）了几个硬编码默认值，你或许需要rebase master之后重新调整一下

rebase了，而且排查调整了其它几个没发现的硬编码默认值。

2023-12-05 05:09 UTC, Xiangze-Li approved these changes
I'm happy

2023-12-05 05:26 UTC, oissevalt approved these changes
LGTM

2023-12-08 10:20 UTC, merged