imp: 将刷屏检测作为单独函数并加入 ReplyToSender 等
sealdice/sealdice-core pull request #467
Opened 2023-12-04 16:27 UTC by oissevalt

closes https://github.com/sealdice/sealdice-core/issues/466

See also: https://github.com/sealdice/sealdice-core/issues/228

2023-12-04 16:36 UTC, JustAnotherID submitted a review, later dismissed
LGTM

2023-12-05 02:29 UTC, Xiangze-Li reviewed
写法上的建议

2023-12-05 02:29 UTC, Xiangze-Li commented on dice/im_helpers.go
> +	if !ctx.Player.RateLimiter.Allow() {
减少嵌套的写法：
```go
if Allow() {
    RateLimitWarned = false
    return false
} 

if RateLimitWarned {
    // ...
} else {
    // ...
}
return true
```

2023-12-05 02:32 UTC, Xiangze-Li commented
另外，如果这样修改后，似乎会让原本只在QQ生效的频率限制对其他平台也生效？

可以作为一个 feature，但这是期望的吗？

2023-12-05 02:36 UTC, oissevalt commented
另发现，现在的设计会使 spam check 在指令执行和消息发送时运行两次

2023-12-05 02:40 UTC, Xiangze-Li requested changes
我先拦一下合并，等问题明确了再改状态

2023-12-05 02:42 UTC, oissevalt commented on dice/im_helpers.go
> +	if !ctx.Player.RateLimiter.Allow() {
似乎不是正确的逻辑？在 !Allow() 时，RateLimitWarned 也不会为 true

2023-12-05 02:54 UTC, Xiangze-Li commented on dice/im_helpers.go
> +	if !ctx.Player.RateLimiter.Allow() {
那么你需要检查现有逻辑的正确性了，因为两种写法是等价的

2023-12-05 03:22 UTC, Xiangze-Li approved these changes
LGTM，实地测试过就OK了

2023-12-05 03:29 UTC, merged