feat: 基本实现了sealchat的接入
sealdice/sealdice-core pull request #469
Opened 2023-12-04 18:21 UTC by fy0

还可能有改动

2023-12-05 03:47 UTC, Szzrain commented
probably solve #59

2023-12-05 03:52 UTC, Xiangze-Li commented
> probably solve #59

并非如此。仍然需要：
1. 能方便切换的预设身份（而不是必须手动维护多个账号）
2. （可选）直接嵌入 WebUI

2023-12-05 10:34 UTC, Xiangze-Li requested changes
建议的写法调整

2023-12-05 10:34 UTC, Xiangze-Li commented on dice/platform_adapter_sealchat.go
> +			// nolint:exhaustive
不建议使用这个 nolint。对于不处理的情况，直接留一个空 defualt 即可；对于不应出现的情况，应当进行适当的 error log。

2023-12-05 10:34 UTC, Xiangze-Li commented on dice/platform_adapter_sealchat.go
> +	fmt.Println("msg", ev.Type, ev)
使用 Logger 或去掉输出

2023-12-05 10:34 UTC, Xiangze-Li commented on dice/platform_adapter_sealchat.go
> +	fmt.Println("!!!", scMsg.Member, "|", scMsg.User.Name)
使用 Logger 或去掉输出

2023-12-05 10:34 UTC, Xiangze-Li commented on dice/platform_adapter_sealchat.go
> +		// fmt.Println("??", k, v)
调试用代码可以删掉

2023-12-05 13:30 UTC, fy0 commented on dice/platform_adapter_sealchat.go
> +			// nolint:exhaustive
原来使用空default就行了

2023-12-05 13:31 UTC, fy0 commented on dice/platform_adapter_sealchat.go
> +	fmt.Println("msg", ev.Type, ev)
还在测试阶段 等测好了删除

2023-12-05 13:34 UTC, Xiangze-Li commented on dice/platform_adapter_sealchat.go
> +			// nolint:exhaustive
这个 linter 的本意是提醒你确认没有漏情况. 用 default 就表明 "剩下的情况我考虑过了, 可以统一处理"

2023-12-10 13:16 UTC, fy0 commented on api/conn.go
> +				case "SEALCHAT":
未来重构时修改吧

2023-12-10 13:22 UTC, Xiangze-Li approved these changes
LGTM

2023-12-10 13:22 UTC, merged