feat(def): 新增快捷指令命令 .def
sealdice/sealdice-core pull request #488
Opened 2023-12-13 17:12 UTC by JustAnotherID

2023-12-13 20:55 UTC, Xiangze-Li commented
有必要做检查，确保 别名 不是可执行的语句。

否则可能出现 `def rd r 100` 这种灌铅操作。

又：虽然顺着梨使用了 define / marco 的术语，但这个实现的确是 alias 的模式。区别是：后者只有指令部分会进行 all or nothing 的完整替换，前者会对全文做子字符串匹配替换。

2023-12-13 21:31 UTC, Xiangze-Li requested changes

2023-12-13 21:31 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +			playerVars := ctx.LoadPlayerGlobalVars()
目前写死了是别名跟着用户走，考虑使用一个 flag 指定定义别名的位置？

我的想法是默认跟着用户走，如果要定义在群聊里需给 flag

```
.def alias cmd --def:group
```

在解析时去掉 `def:group` 这个 flag。

2023-12-13 21:31 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +			case "del":
加一个 `def clear`

2023-12-13 21:31 UTC, Xiangze-Li commented on dice/im_session.go
> +							log.Infof("快捷指令解析失败，继续使用原命令")
不必 log，这种情况反而应该是普遍的，会造成 spam

2023-12-13 21:31 UTC, Xiangze-Li commented on dice/im_session.go
> +				targetCmdArgs := cmdArgs
似无必要加这个变量？在解析到别名时直接替换掉 `cmdArgs` 即可。

2023-12-13 21:31 UTC, Xiangze-Li commented on dice/im_session.go
> +							targetCmdArgs = _target
原来 `cmdArgs` 中的参数是否被丢弃了？这或许是不希望的。

考虑如下用法：

```
.def 查询coc find --group=COC
.查询coc 克苏鲁 --num=10
```

可以期望 等价于执行 `.find --group=COC 克苏鲁 --num=10`

2023-12-13 21:32 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +				name := action
有必要做检查，确保 别名 不是可执行的语句。

否则可能出现 `def rd r 100` 这种灌铅操作。

2023-12-13 21:34 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +				name := action
（一些日经兼容性发电）

哎，兼容性。

如果强制加空格，这里的限制可以大大简化成「别名不是指令」。

2023-12-14 01:47 UTC, JustAnotherID commented on dice/builtin_commands.go
> +			playerVars := ctx.LoadPlayerGlobalVars()
alias 定位我认为是个比较私人的设置，限制在群聊感觉意义不大。同时这个参数输入也很麻烦，不像命令行中有补全输入那样方便。暂时先不考虑添加，如果后续真有需要再加上不迟。

2023-12-14 01:52 UTC, JustAnotherID commented on dice/im_session.go
> +							log.Infof("快捷指令解析失败，继续使用原命令")
其实这个不是普遍情况，普遍情况是在上面 `ValueMap.Get` 为空时直接返回。这里是 alias 的命令无法执行的时候走的流程，感觉还是有必要的。

2023-12-14 02:30 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +			playerVars := ctx.LoadPlayerGlobalVars()
在群聊使用是另一个场景，即，在某一个团中会频繁进行某种别处用不到的复杂操作，通过别名来简化输入。

这时，应当希望一个人设置后其他人也能利用，而不希望这个别名泄露到其他地方。

2023-12-14 02:33 UTC, Xiangze-Li commented on dice/im_session.go
> +							log.Infof("快捷指令解析失败，继续使用原命令")
有道理，不过这种情况还可以有优化：

1. 这是预期外的错误情况，使用日志等级 Error 
2. 把未能解析的别名指令记录在日志里
3. （？）给设置别名的用户发送消息提醒

2023-12-14 02:36 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +			playerVars := ctx.LoadPlayerGlobalVars()
如果加参数比较复杂，考虑使用两个指令名 `def` 和 `defgroup`，两者可以共用同一个后端，用判断指令名替代判断 flag 是否存在

2023-12-27 09:09 UTC, Xiangze-Li reviewed
请参考评论

2023-12-27 09:09 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +				VarSetValueStr(ctx, "$t指令来源", "个人")
建议至少提供一个key和valve都全都是ascii字符的变量，以便复杂文案中的嵌入脚本调用。

2023-12-27 09:09 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +							ctx.AliasPrefixText = DiceFormatTmpl(ctx, "核心:快捷指令触发_前缀")
从防止灌铅的角度说，如果这个前缀被设置为空，应当使用一个硬编码的默认值，而不是放任为空。

2023-12-27 10:31 UTC, JustAnotherID commented on dice/builtin_commands.go
> +							ctx.AliasPrefixText = DiceFormatTmpl(ctx, "核心:快捷指令触发_前缀")
换成指令方案以后防止灌铅的需求不是那么紧迫了，无法实现和内置指令一致的，下放到骰主控制我认为是可以接受的。
有默认值会破坏和其它自定义文案的行为一致性。~~主要是现在的自定义文案系统支持不了必填。~~

2023-12-27 10:33 UTC, JustAnotherID commented on dice/builtin_commands.go
> +				VarSetValueStr(ctx, "$t指令来源", "个人")
有这个需要吗，其它的变量似乎都没有提供。

2023-12-27 10:33 UTC, Xiangze-Li commented
好习惯从我做起（）&nbsp;

李祥泽


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年12月27日(星期三) 晚上6:33
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; "Review ***@***.***&gt;; 
Subject: Re: [sealdice/sealdice-core] feat(def): 新增快捷指令命令 .alias (PR #488)





 
@JustAnotherID commented on this pull request.
 
 
In dice/builtin_commands.go:
 &gt; + +			_isGroup := cmdArgs.GetKwarg("g") +			isGroup := _isGroup != nil +			if isGroup &amp;&amp; ctx.MessageType != "group" { +				ReplyToSender(ctx, msg, DiceFormatTmpl(ctx, "核心:快捷指令_非群聊")) +			} else { +				ctx.LoadGroupVars() +			} + +			playerVars := ctx.LoadPlayerGlobalVars() +			switch action := args[0]; action { +			case "del", "rm": +				name := args[1] +				key := "$m:alias:" + name +				m := playerVars.ValueMap +				VarSetValueStr(ctx, "$t指令来源", "个人")  
有这个需要吗？其它的变量似乎都没有提供。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2023-12-27 10:35 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +				VarSetValueStr(ctx, "$t指令来源", "个人")
好习惯从我做起

2023-12-27 11:02 UTC, JustAnotherID commented on dice/builtin_commands.go
> +				VarSetValueStr(ctx, "$t指令来源", "个人")
讨论后这块单独提 issue 处理。

2023-12-27 11:22 UTC, fy0 commented on dice/builtin_commands.go
> +			args := cmdArgs.Args
此处应有chop切开子命令

2023-12-27 11:24 UTC, fy0 commented
优先群内快捷，其次才是个人，这样会不会好些

2023-12-28 01:40 UTC, JustAnotherID commented
> 优先群内快捷，其次才是个人，这样会不会好些

目前的行为就是这样的。

2023-12-28 12:12 UTC, fy0 commented
> > 优先群内快捷，其次才是个人，这样会不会好些
> 
> 目前的行为就是这样的。

意思是说包括定义的部分

2023-12-28 13:29 UTC, fy0 approved these changes
~~那么，先合并了~~ 等等 还有requst没结束

2023-12-28 13:30 UTC, fy0 submitted a review, later dismissed

2023-12-28 13:45 UTC, JustAnotherID commented on dice/builtin_commands.go
> +			args := cmdArgs.Args
会导致如 `.alias helpC .help #COC` 形式的快捷指令无法被定义，不添加切割命令。

2023-12-28 14:04 UTC, JustAnotherID commented
> > > 优先群内快捷，其次才是个人，这样会不会好些
> > 
> > 
> > 目前的行为就是这样的。
> 
> 意思是说包括定义的部分

已调整

2023-12-29 00:01 UTC, Xiangze-Li approved these changes
LGTM

2023-12-29 00:01 UTC, merged