feat: 初步实现消息修改方法和事件
sealdice/sealdice-core pull request #502
Opened 2023-12-26 18:14 UTC by oissevalt

- 向 PlatformAdapter 添加 EditMessage 和 RecallMessage 方法
- 为 KOOK 和 Discord 适配器实现上述方法
- 向 IMSession 添加 OnMessageEdit 方法

2023-12-27 03:11 UTC, JustAnotherID requested changes

2023-12-27 03:11 UTC, JustAnotherID commented on dice/platform_adapter_gocq_actions.go
> +func (pa *PlatformAdapterGocq) EditMessage(_ *MsgContext, _, _ string) {}
空实现是否增加日志提醒收到消息修改/撤回事件但目前不支持？下同

2023-12-27 09:15 UTC, Xiangze-Li reviewed
最后实现的是不加处理地直接修改原始记录吗？

白费我许多脑细胞（）

2023-12-27 09:15 UTC, Xiangze-Li commented on dice/ext_log.go
> +	err := model.LogEditByMsgID(ctx.Dice.DBLogs, groupID, logName, content, messageID)
可以考虑把 sql.ErrNoRows 的特判放进 model 包内部，这样就无需在业务逻辑里考虑 sql 的问题了。

2023-12-27 09:51 UTC, oissevalt commented
> 最后实现的是不加处理地直接修改原始记录吗？
> 
> 白费我许多脑细胞（）

先实现了再去讨论的，不过数据库我还没搞明白，加字段什么操作先等等

2023-12-30 12:19 UTC, Xiangze-Li requested changes
SQL 的写法需要推敲

2023-12-30 12:19 UTC, Xiangze-Li commented on dice/model/log.go
> +	_, err = db.Exec("SELECT * FROM log_items WHERE log_id = ? AND raw_msg_id = ?", logID, rid)
有必要先 SELECT 再 UPDATE 吗？

如果这个 raw_mgs_id 不存在，UPDATE 时就不会更新任何行，这时过滤掉 ErrNoRows 就好了。

2023-12-30 12:19 UTC, Xiangze-Li commented on dice/platform_adapter.go
> +	EditMessage(ctx *MsgContext, msgID, message string)
（并非要求修改）由海豹核心主动去修改/撤回消息其实是比较罕见的情况？

2023-12-30 15:05 UTC, oissevalt commented on dice/platform_adapter.go
> +	EditMessage(ctx *MsgContext, msgID, message string)
这个大部分平台是空实现，Discord 和 KOOK 的实现没有用到，留待以后吧

2023-12-31 13:09 UTC, Xiangze-Li approved these changes
lgtm

2023-12-31 13:10 UTC, merged