fix: 修复规则书规则带难度时大失败判定线问题
sealdice/sealdice-core pull request #527
Opened 2024-01-05 09:49 UTC by fy0

先review一下 还有一个rcv的migrate

2024-01-05 09:58 UTC, Xiangze-Li requested changes

2024-01-05 09:58 UTC, Xiangze-Li commented on dice/ext_coc7.go
> +				VarSetValueInt64(ctx, "$t玩家A判定值", outcome1) // 这两个由下面的替换
如果决定做包括migration的修改，就直接删掉旧变量

2024-01-05 09:58 UTC, Xiangze-Li commented on dice/ext_coc7.go
> +							"outcome": d100,
需要确认影响范围，应该会包括染色器？

2024-01-05 10:34 UTC, fy0 commented on dice/ext_coc7.go
> +				VarSetValueInt64(ctx, "$t玩家A判定值", outcome1) // 这两个由下面的替换
出于向下兼容考虑，再支持一段时间

2024-01-05 10:35 UTC, fy0 commented on dice/ext_coc7.go
> +							"outcome": d100,
是的 染色器另外改

2024-01-05 10:36 UTC, fy0 commented
影响范围：ra、rav、sc、染色器(转回声log)

2024-01-05 10:40 UTC, fy0 commented
#526

2024-01-06 08:33 UTC, fy0 commented
已经完成染色器的适配（只影响转为回声工坊）

2024-01-06 10:43 UTC, Xiangze-Li reviewed
代码逻辑没有发现问题，但我个人不赞同随 1.4.3 版本发布这个修改

2024-01-06 12:17 UTC, fy0 commented
> 代码逻辑没有发现问题，但我个人不赞同随 1.4.3 版本发布这个修改

但是。。。规则实现有点问题的话 会不会不是很妙

2024-01-06 12:18 UTC, Xiangze-Li commented
> > 代码逻辑没有发现问题，但我个人不赞同随 1.4.3 版本发布这个修改
> 
> 但是。。。规则实现有点问题的话 会不会不是很妙

没被发现就是没问题

2024-01-06 15:42 UTC, fy0 commented
> > > 代码逻辑没有发现问题，但我个人不赞同随 1.4.3 版本发布这个修改
> > 
> > 
> > 但是。。。规则实现有点问题的话 会不会不是很妙
> 
> 没被发现就是没问题

那就暂定推后发布

2024-01-10 09:55 UTC, merged