impl(log):海豹染色器分页上传及对应的染色器后端API
sealdice/sealdice-core pull request #576
Opened 2024-02-13 15:16 UTC by PaienNate

该PR试图以分页的方式解决过大的LOG在前端解压时，导致爆内存的问题。

已根据Szz大佬的提示修改为新的接口，不对原本的代码做任何更改~~（昨天写嗨了真是写糊涂了）~~

其思路为：

以5000页为一个单位，使用 @JustAnotherID 的分页方法将整个日志分成N页，记作**总页码**；之后将每一页的zlib压缩后的数据计算**md5**，以此作为访问该数据的key上传到后端；再将页码作为键，对应页码的md5作为值，和总页码一起拼凑为“元数据”。

后端收到元数据后，生成key+password作为元数据的键。当染色器访问时带前端页码，页码会在后端经过元数据转换为md5，再通过md5转换为数据，从而生成和原染色器相同的返回数据（以达到少改动对应前端代码的目的）。同时在返回数据中添加总页码数，以辅助前端确认总页码。

大费周章的主要原因是这样能更好的支持KV类型的数据库。~~（毕竟这个数据库能白嫖）~~，理论上在Go等开发语言上进行实现或者迁移该方案并不困难。

该项目的后端（基于Cloudflare Worker）已经完成，在我的仓库[点这里](https://github.com/PaienNate/cf_sealdice_logbackend/tree/dev) dev分支，同时提供了API说明文档可供参考。

~~对应染色器部分我已经拉朋友在研究了。~~

Close #539

2024-02-15 23:25 UTC, Xiangze-Li requested changes
另外有一点不相关讨论：

在主干代码中单独增加对接个别第三方服务的逻辑是否是合适的？

另一个思路是：暴露获取 Log 的接口给 JS（比如封装 `model.GetLogLinesPage`），则可以通过 JS 插件对接任意的第三方后端。

2024-02-15 23:25 UTC, Xiangze-Li commented on dice/ext_log.go
> +
根据 go 风格规范，此处不应空行

2024-02-15 23:25 UTC, Xiangze-Li commented on dice/ext_log.go
> +func CalculateMD5(input []byte) string {
如果要封这个函数，放到 utils 目录去

2024-02-15 23:27 UTC, Xiangze-Li commented on dice/ext_log.go
> +		// TODO:Log上传后又有更新，理论上应当更新原本的日志吧？考虑到潜在的海豹爆炸导致的安全性问题，多上传就多上传吧……
原有逻辑是对接海豹染色器后端的。如果你的后端支持更新原来的上传，这确实是更合理的。

2024-02-15 23:33 UTC, Xiangze-Li commented on dice/ext_log.go
> +	// 方便KV数据库存储。
这样的数据便于 KV 数据库直接存储，但是在生成和处理时，这样的动态 key 是不方便的。

考虑把数据的处理传输和存储格式分开，在处理传输时仍然使用数组，落盘读盘过程中再转换成你设计的格式。

```json
{
  "page_num": 3,
  "checksums": [
    "MD5_1", "MD5_2", "MD5_3"
  ]
}
```

2024-02-15 23:59 UTC, PaienNate commented on dice/ext_log.go
> +	// 方便KV数据库存储。
一开始我的考虑也是传输数组。但我不清楚不同语言在读取同一个json时，列表顺序是否会发生变化。若会的话，逻辑几乎无法检查。这会导致分页出现问题，因为失去了标识关系。

2024-02-16 00:24 UTC, Xiangze-Li commented on dice/ext_log.go
> +	// 方便KV数据库存储。
列表的顺序是安全的

2024-02-16 00:29 UTC, PaienNate commented on dice/ext_log.go
> +	// 方便KV数据库存储。
那就没有问题了，回头改掉。

2024-02-16 00:43 UTC, PaienNate commented
> 另外有一点不相关讨论：
> 
> 在主干代码中单独增加对接个别第三方服务的逻辑是否是合适的？
> 
> 另一个思路是：暴露获取 Log 的接口给 JS（比如封装 `model.GetLogLinesPage`），则可以通过 JS 插件对接任意的第三方后端。

个人提出该PR的重要想法是：试图借助此PR，确定一个公共使用的，更好的染色器后端接口（可以参见我后端仓库内的简易API文档），之后其他的第三方服务仅需要实现描述的后端接口，即可直接以修改后端地址的形式完成染色器后端的迁移。

目前的染色器后端接口可以说和个网盘上传下载差不多……目前已经有遇到大文件导致染色器加载缓慢/无法上传的问题，同时有比如重复上传而非更新，缺少自定义搭建时的鉴权方式等问题，个人认为重构是迟早的事情。

对于暴露LOG的接口给JS，大部分用户使用染色器目前的功能似乎已经非常满足？目前除了大文件无法上传的问题以外，看骰主的说法，好像并没有什么其他的问题。感觉等骰主专门有对应的想法再做不迟。

2024-02-16 10:18 UTC, fy0 commented
有一点不明白，核心问题是过大的log数据解压时会爆掉对吧。
其实这好像是一个实现问题，因为zlib可以流式解压，但是story painter中没有这么做（因为当时没想到会有那么大的log）

另外最大的失误其实是没有弄成一行log一个json这种形式，因为json得整体解析（虽然也有stream的json解析，但是我也没有用过）。
如果弄一个V2版本的日志的话，应该是这样：
第一行: 一个json object，解析得到日志基本信息
第二行到第N行: 每行一句对话

2024-02-16 10:19 UTC, JustAnotherID requested changes

2024-02-16 10:19 UTC, JustAnotherID commented on dice/utils_log_upload.go
> +	req, err := http.NewRequest(http.MethodPut, backendURL+"/dice/api/log", body)
`/dice/api/log` 这个路径写死合适吗？如果考虑后期开放设置项的话，这里最好也是个参数

2024-02-16 10:19 UTC, JustAnotherID commented on dice/ext_log.go
> +			fmt.Println(err)
```suggestion
			ctx.Dice.Logger.Error(err)
```

2024-02-16 10:22 UTC, PaienNate commented
> 有一点不明白，核心问题是过大的log数据解压时会爆掉对吧。 其实这好像是一个实现问题，因为zlib可以流式解压，但是story painter中没有这么做（因为当时没想到会有那么大的log）
> 
> 另外最大的失误其实是没有弄成一行log一个json这种形式，因为json得整体解析（虽然也有stream的json解析，但是我也没有用过）。 如果弄一个V2版本的日志的话，应该是这样： 第一行: 一个json object，解析得到日志基本信息 第二行到第N行: 每行一句对话

https://myseal.firehomework.top/?key=PJky#650911 这是一只炸了的豹，唔，然后草啊zlib居然能流式传输——

2024-02-23 13:05 UTC, JustAnotherID commented
讨论后决定应当采用流式传输方案，关闭当前pr。

2024-02-23 13:05 UTC, closed without merging