chore: 依据 Go Uber 格式规范，重新格式化代码
sealdice/sealdice-core pull request #584
Opened 2024-02-17 02:48 UTC by oissevalt

主要包括：

1. 依照 标准库—本地库—第三方库 的顺序排列 import

2. 对长度超过 120 字符的行进行换行

以下是 GoLand 的相关设置：

![Wrapping and Braces](https://github.com/sealdice/sealdice-core/assets/57583509/fa377a6e-dc51-45c2-9b59-d584be94af6e)

![Imports](https://github.com/sealdice/sealdice-core/assets/57583509/9328fb5f-cbef-45aa-927c-d219065330cb)

*(ref: xxjwxc/uber_go_guide_cn)*

2024-02-17 04:08 UTC, fy0 commented
![SHA`G$IV FB PFKJ(LV@YGB](https://github.com/sealdice/sealdice-core/assets/1579850/e1264b42-bba7-47cc-a1b0-83be58ba8e8b)
感觉import排序是好的，换行还规则是不要力，这个应该会和大多数ide的默认配置打架

2024-02-20 01:56 UTC, Xiangze-Li requested changes
涉及编辑器配置的规范性修改，请把编辑器的设置文件附带进来，以确保所有编辑者使用相同的配置。

如 VSC 的 `.vscode/settings.json`。

2024-02-20 01:56 UTC, Xiangze-Li commented on readme.md
> +本项目使用 golangci-lint
不要在 MarkDown 中使用自动换行。一些渲染器会将无空行的换行渲染为软换行（`<br/>`）。

2024-02-23 12:49 UTC, JustAnotherID requested changes
也同意将强制换行的规则拿掉，只保留import顺序规则的意见。

2024-02-25 16:01 UTC, closed without merging