feat(satori-protocol): 增加 satori 协议适配
sealdice/sealdice-core pull request #630
Opened 2024-03-08 18:02 UTC by JustAnotherID

ui 调整：sealdice/sealdice-ui#162

2024-03-08 23:03 UTC, Xiangze-Li requested changes

2024-03-08 23:04 UTC, Xiangze-Li commented
tmd我下次周末一定要带至少一个大屏幕回家，用手机 review 代码太痛苦了

2024-03-09 05:56 UTC, JustAnotherID commented on dice/platform_adapter_satori.go
> +}
按协议规定只返回Message数组，所以能序列化成功就是正确响应了

2024-03-09 05:56 UTC, JustAnotherID commented on dice/platform_adapter_satori_entity.go
> +	SatoriTextChannel     SatoriChannelType = iota // 文本频道
0 是文本频道是由协议规定的

2024-03-09 07:37 UTC, JustAnotherID commented on dice/platform_adapter_satori.go
> +				msgType, msgData, err := conn.ReadMessage()
应该不是阻塞的？官方demo也是这么写的

2024-03-09 07:37 UTC, JustAnotherID commented on dice/platform_adapter_qq_helper.go
> +			if waitTimes > 5 {
看逻辑似乎没有这样的问题

2024-03-18 01:34 UTC, Xiangze-Li commented on dice/platform_adapter_satori.go
> +						pa.CancelFunc()
是否需要把 `pa.CancelFunc()` 也置空?

2024-03-18 02:16 UTC, Xiangze-Li approved these changes
LGTM

2024-03-18 02:27 UTC, merged