feat(JS): JS 插件元数据增加海豹版本限制字段
sealdice/sealdice-core pull request #649
Opened 2024-03-15 17:28 UTC by JustAnotherID

`@sealLowestVersion` 限制海豹最低版本，填入指定的最低版本号。
`@sealVersion` 限制海豹版本范围，需要满足 semver 版本范围语法。
可同时存在多个，需要同时满足。

Close #615

2024-03-15 22:41 UTC, Xiangze-Li requested changes

2024-03-15 22:41 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +					d.Logger.Error("读取内置脚本失败(错误依赖):\n", err.Error())
Nit：不建议在日志中换行。每行日志开头的时间前缀并不会加在新行上，造成日志文件中比较混乱。

2024-03-15 22:41 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +				if !lowestVersionRe.Match([]byte(v)) {
直接使用 MatchString

2024-03-15 22:41 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +				vc, _ := semver.NewConstraint(">=" + v + "-0")
注释说明添加 `"-0"` 的作用以防误删

2024-03-15 22:41 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +					errMsg = append(errMsg, fmt.Sprintf("插件「%s」限制海豹版本的格式不正确，应满足 semver 版本范围语法", jsInfo.Name))
不正确的参数 `v` 记录在日志中

2024-03-15 22:41 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +				vc, err := semver.NewConstraint(v)
这种约束无法自动适配 dev 和 rc 版本？

2024-03-16 06:02 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +				vc, err := semver.NewConstraint(v)
此处是打算交给插件作者决定是否适配，通常情况下都更建议使用 `@sealLowestVersion`。

2024-03-16 06:06 UTC, Xiangze-Li commented on dice/dice_jsvm.go
> +				vc, err := semver.NewConstraint(v)
这样的话, 考虑把 `sealVersion` 这个短名字留给更常用的项, 这里可以叫 `sealVersionRaw` 或 `sealVersionExact`

2024-03-16 06:08 UTC, Xiangze-Li approved these changes
LGTM with suggestion

2024-03-16 06:11 UTC, Xiangze-Li approved these changes
LGTM

2024-03-16 06:14 UTC, JustAnotherID commented
leave the decision to @fy0

2024-03-16 07:44 UTC, fy0 reviewed
还没上车 怎么忽然关了

2024-03-16 07:45 UTC, fy0 commented
感觉像是包管理那样只留一个版本号就行？

2024-03-16 10:47 UTC, closed without merging

2024-03-16 10:48 UTC, JustAnotherID commented
See #652