feat(QQ): 实现内置 lagrange 的原型版本
sealdice/sealdice-core pull request #668
Opened 2024-03-23 12:37 UTC by JustAnotherID

2024-03-23 12:45 UTC, Xiangze-Li commented on dice/platform_adapter_gocq.go
> +		if pa.BuiltinMode != "gocq" {
`pa.BuiltinMode == "lagrange"` 以防有留空的旧连接

2024-03-23 13:01 UTC, Xiangze-Li requested changes

2024-03-24 06:57 UTC, JustAnotherID commented on api/api_bind.go
> +	e.POST(prefix+"/im_connections/add", ImConnectionsAddBuiltinGocq)
移除 or 替换 api 还是考虑稳定以后的版本中再进行。

2024-03-25 01:54 UTC, Xiangze-Li commented on dice/platform_adapter_lagrange_helper.go
> +		exeFilePath = strings.ReplaceAll(exeFilePath, "\\", "/") // windows平台需要这个替换
考虑用 `filepath.ToSlash`？


```suggestion
		exeFilePath = filepath.ToSlash(exeFilePath) // windows平台需要这个替换
```

2024-03-25 18:05 UTC, Szzrain requested changes

2024-03-25 18:05 UTC, Szzrain commented on dice/platform_adapter_lagrange_helper.go
> +			dst, err := os.OpenFile(exeFilePath, os.O_WRONLY|os.O_CREATE, 0o755)
这里需要递归 copy 整个文件夹以适配 Android 端，或者如果有办法改变 subprocess 的 workdir 也行？还需要测试一下子进程是否继承了父进程的环境变量，如果没有的话需要手动设置一下

2024-03-26 01:41 UTC, Xiangze-Li requested changes

2024-03-26 01:41 UTC, Xiangze-Li commented on dice/platform_adapter_gocq_helper.go
> +	if pa.UseInPackGoCqhttp && pa.BuiltinMode == "gocq" { //nolint:nestif
会不会存在 `pa.BuiltinMode` 为空字符串的情况？

2024-03-26 01:41 UTC, Xiangze-Li commented on dice/platform_adapter_lagrange_helper.go
> +		isSeldKilling := false
疑似 typo：Seld -> Self？

2024-04-01 20:51 UTC, Szzrain commented on dice/platform_adapter_gocq_helper.go
> +	if pa.UseInPackGoCqhttp && pa.BuiltinMode == "gocq" { //nolint:nestif
除非手动修改过 serve.yaml 否则不会

2024-04-02 01:21 UTC, Xiangze-Li requested changes

2024-04-02 01:21 UTC, Xiangze-Li commented on dice/platform_adapter_lagrange_helper.go
> +			pa.ConnectURL = fmt.Sprintf("ws://localhost:%d", p)
需要改成 `127.0.0.1`，参考 https://github.com/KonataDev/Lagrange.Core/issues/264

2024-04-02 08:58 UTC, fy0 approved these changes
进入测试

2024-04-02 09:07 UTC, merged