feat(js): base64 转图片 API
sealdice/sealdice-core pull request #722
Opened 2024-04-14 03:20 UTC by yichere

新增 JS API，eg：seal.replyToSender(ctx,msg,`[CQ:image,file=${seal.base64ToImage(basevalue)}]`)

2024-04-14 10:40 UTC, Xiangze-Li commented
@yichere 似乎有重复文件，请清理一下你的提交

2024-04-18 01:20 UTC, Szzrain requested changes

2024-04-18 01:20 UTC, Szzrain commented on dice_base.go
> +package dice
这个文件重复了，另：建议新开一个utils包然后把这个文件放在那里面

2024-04-20 14:00 UTC, Xiangze-Li commented on utils/dice_base.go
> +				logger.Errorf("创建文件出错%s", err.Error())
```suggestion
			errClose := fi.Close()
			if errClose != nil {
				logger.Errorf("关闭文件出错%s", errClose.Error())
```

2024-04-20 14:13 UTC, JustAnotherID approved these changes
LGTM

2024-04-20 14:14 UTC, merged