fix(plugin):试图解决插件并发导致的海豹莫名闪退问题。
sealdice/sealdice-core pull request #750
Opened 2024-04-26 05:56 UTC by PaienNate

试图 Close #749 的一些尝试，在唯一收集到的案例上目前工作正常。因无力继续研究，故放出修复方式供探讨。

2024-04-28 11:48 UTC, Xiangze-Li submitted a review, later dismissed

2024-04-28 11:48 UTC, Xiangze-Li commented on main.go
> +							exec.Command("pause") // windows专属
win专属到逻辑需要用 `GOOS == "windows"` 或类似逻辑控制起来，避免其他平台兼容性问题

2024-04-28 11:48 UTC, Xiangze-Li commented on dice/ext.go
> +	} else {
return 之后不需要再 else

这里没有被 linter 大爷跳问题吗？

2024-04-28 11:48 UTC, Xiangze-Li commented on dice/ext.go
> +		err := i.Storage.Close()
没有关闭成功的 i.Storage 可以直接置成 nil 吗？是否会导致文件handle泄露？

2024-04-28 11:48 UTC, Xiangze-Li commented on dice/ext.go
> +		return err
是否需要将 i.init 置为 false？

2024-04-28 13:59 UTC, JustAnotherID requested changes

2024-04-28 13:59 UTC, JustAnotherID commented on dice/dice.go
> +	mu   sync.Mutex `yaml:"-"` // 互斥锁
换个更有意义的名字比如 dbMu？

2024-04-28 13:59 UTC, JustAnotherID commented on dice/ext.go
> +	// d.Logger.Infof("[插件]：%s 正在尝试获取锁进行初始化", i.Name)
日志都打了，干脆用 d.Logger.Debugf 吧

2024-04-28 13:59 UTC, JustAnotherID commented on dice/ext.go
> +		// d.Logger.Info("[插件]:初始化调用，但数据库已经加载")
同上，干脆用 d.Logger.Debugf 吧

2024-04-28 13:59 UTC, JustAnotherID commented on dice/ext.go
> +		d.Logger.Error(err.Error())
与上一条合并一下？

2024-04-28 13:59 UTC, JustAnotherID commented on dice/ext.go
> +			return errors.New("Storage初始化错误")
error 信息不要以大写字母开头

2024-04-28 13:59 UTC, JustAnotherID commented on dice/im_session.go
> +			// 暂时不知道用啥Logger
用 ei.dice.Logger 吧？

2024-04-29 01:27 UTC, Xiangze-Li commented on dice/dice.go
> +	mu   sync.Mutex `yaml:"-"` // 互斥锁
mutex 如果缩写还是缩写成 mux 较好

2024-04-29 01:31 UTC, PaienNate commented on dice/dice.go
> +	mu   sync.Mutex `yaml:"-"` // 互斥锁
讨论个名字罢.jpg

2024-04-29 09:08 UTC, PaienNate commented on dice/ext.go
> +		err := i.Storage.Close()
修正了一下，但不清楚是否修正的正确

2024-04-30 08:29 UTC, JustAnotherID approved these changes

2024-04-30 08:32 UTC, merged