feat(js):新增系列api
sealdice/sealdice-core pull request #756
Opened 2024-04-26 16:21 UTC by yichere

修复`baseToImage`api，新增`log`，`errorlog`，`writeFile`api

2024-04-26 17:24 UTC, JustAnotherID requested changes

2024-04-26 17:24 UTC, JustAnotherID commented on dice/js_api.go
> +			// 出现错误，拒绝向下执行
都不执行了为什么不 `return ""`

2024-04-26 17:24 UTC, JustAnotherID commented on dice/js_api.go
> +		path := filepath.Join("plugin", ei.Name)
这个文件夹不对，应该限制在 `default/extensions/<ext>` 目录下，和 ext 本身会有的 `storage.db` 目录相同，防止插件越权写入。

2024-04-26 17:24 UTC, JustAnotherID commented on dice/js_api.go
> +			logger.Errorf("写入文件出错:", err)
```suggestion
			logger.Errorf("写入文件出错:%s", err)
```

2024-04-26 17:24 UTC, JustAnotherID commented on dice/dice_jsvm.go
> +		_ = seal.Set("writeFile", FileWrite(d.Logger))
挂到 ext 上面去，类似 `func (i *ExtInfo) StorageGet(k string)`

2024-04-27 04:44 UTC, yichere commented
![image](https://github.com/sealdice/sealdice-core/assets/164668043/7ab10ced-8cd6-473c-af06-290f3002b645)
使用绝对路径错误提示
![image](https://github.com/sealdice/sealdice-core/assets/164668043/58c7b853-39ce-4ce3-bb90-6ea33613ab41)

2024-04-27 06:34 UTC, Xiangze-Li requested changes

2024-04-27 06:34 UTC, Xiangze-Li commented on dice/js_api.go
> +		file, err := os.OpenFile(path+"/"+name, os.O_CREATE|os.O_WRONLY, 0644) // 创建或打开文件
攻击面：如果 `name` 中含有多个 `..`，使拼接后的路径超出控制，如：

`name = ../../serve.yaml`
`data/default/extensions/EXT_NAME/../../serve.yaml`

2024-04-30 02:42 UTC, Xiangze-Li commented
@yichere 请更改有问题的写法

2024-05-02 16:23 UTC, closed without merging