feat(js)：新增系列 JS API
sealdice/sealdice-core pull request #766
Opened 2024-05-02 17:56 UTC by yichere

新增了 `seal.log`,`seal.errorlog`,`ExtInfo.fileWrite/Read`api

2024-05-03 01:32 UTC, Xiangze-Li requested changes
另：不建议关闭前一PR另开新的，这会导致之前的讨论难以找到

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	if re.MatchString(name) {
无效防护：如果name是 A/../../../secret.file

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	if filepath.IsAbs(path) {
无效检查：或许是想判断 IsAbs(name)？

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	file, err := os.OpenFile(path+"/"+name, os.O_CREATE|os.O_WRONLY, 0644) // 创建或打开文件
如果该文件已经存在，采取什么行为？

目前的行为是附加（append），是否应该允许用户选择清除（truncate）和报错？

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	path := filepath.Join("data", "default", "extensions", i.Name, name)
需要防护：name可能含有 ..

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	_, err := os.Stat(filePath)
需要防护：对于不属于此扩展的文件不提供判断

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	return !os.IsNotExist(err)
对于其他错误情况也被视为文件存在，这是预期中的吗？

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +	return !os.IsNotExist(err)
使用 errors.Is

2024-05-03 01:32 UTC, Xiangze-Li commented on dice/js_api.go
> +		logger.Errorf(s)
使用 logger.Error 以减少一次 fmt 调用

2024-05-03 01:37 UTC, yichere commented on dice/js_api.go
> +	if filepath.IsAbs(path) {
它在我的设备上好像工作了？

2024-05-03 01:39 UTC, Xiangze-Li commented on dice/js_api.go
> +	if filepath.IsAbs(path) {
这个判断不是不工作，而是 path 中不包含用户输入，判断固定组合没有意义。

2024-05-03 01:51 UTC, yichere commented on dice/js_api.go
> +	if re.MatchString(name) {
可以选择判断name中是否存在超过两个"."?

2024-05-03 01:55 UTC, Xiangze-Li commented on dice/js_api.go
> +	if re.MatchString(name) {
考虑 filepath.SplitList(name) 之后判断其中任何一个都不是 . 或 ..

2024-05-03 01:57 UTC, yichere commented on dice/js_api.go
> +	_, err := os.Stat(filePath)
意思是将 `filePath`严格限制为相对路径？

2024-05-03 01:57 UTC, Xiangze-Li commented on dice/js_api.go
> +	if re.MatchString(name) {
用 =="." 即可

2024-05-03 01:58 UTC, Xiangze-Li commented on dice/js_api.go
> +	_, err := os.Stat(filePath)
和写文件接口一样的，如果不是本扩展文件都不予判断

2024-05-03 02:00 UTC, Xiangze-Li commented
建议：把判断传入文件路径的逻辑抽出来以私有可见性挂在 ExtInfo 下面

2024-05-03 02:33 UTC, yichere commented on dice/js_api.go
> +	if re.MatchString(name) {
目前采用这种方法是否可行？![image](https://github.com/sealdice/sealdice-core/assets/164668043/94ad2e5d-753d-4283-902d-1462224719eb)

2024-05-03 02:44 UTC, yichere commented on dice/js_api.go
> +	return !os.IsNotExist(err)
是在预期中的，如果不存在报错然后通过error检测文件是否存在
![image](https://github.com/sealdice/sealdice-core/assets/164668043/d191f055-0299-4dcc-bd6f-c45b4738c0fc)

2024-05-03 03:02 UTC, Xiangze-Li commented on dice/js_api.go
> +	if re.MatchString(name) {
逻辑错误。这个正则表达式也会匹配扩展名中的句点

2024-05-03 03:03 UTC, Xiangze-Li commented on dice/js_api.go
> +	file, err := os.OpenFile(path+"/"+name, os.O_CREATE|os.O_WRONLY, 0644) // 创建或打开文件
是append。如果要truncate需要在打开时附上另一个flag

2024-05-03 03:05 UTC, Xiangze-Li commented on dice/js_api.go
> +	return !os.IsNotExist(err)
其他错误：如没有读权限、文件系统错误等

2024-05-03 03:06 UTC, yichere commented on dice/js_api.go
> +	return !os.IsNotExist(err)
通过该扩展创建的文件应该都有权限访问？

2024-05-03 04:11 UTC, Szzrain commented on dice/js_api.go
> +	if !isNotABS(name, i.dice.Logger) {
这里可以参考一下 https://github.com/sealdice/sealdice-core/blob/1be347b813da23e368eadeeba102e332fc12ce7a/message/message.go#L371-L394
只要保证路径在限制范围（插件指定的文件目录）内即可

2024-05-03 04:32 UTC, Szzrain commented on dice/dice_jsvm.go
> +		_ = seal.Set("errorlog", ErrorLog(d.Logger))
这两处的目的是？目前的 `console.log` 已经可以做到打印日志了

2024-05-03 04:35 UTC, Szzrain commented on dice/js_api.go
> +	return func(b64 string) string {
返回时应当把错误也返回，在 goja 中的行为会变成 throw 异常

2024-05-03 04:35 UTC, Szzrain commented on dice/js_api.go
> +		i.dice.Logger.Error(err.Error())
同上，应当返回错误

2024-05-03 06:11 UTC, yichere commented on dice/js_api.go
> +	return func(b64 string) string {
类似于 ```js
func Base64ToImageFunc(logger *zap.SugaredLogger) func(string) (string,error) {
	return func(b64 string) (string ,error){
       ……	
       }
}
```
吗？

2024-05-03 06:18 UTC, yichere commented on dice/dice_jsvm.go
> +		_ = seal.Set("errorlog", ErrorLog(d.Logger))
写的时候不知道可以了（

2024-05-03 06:20 UTC, yichere commented on dice/js_api.go
> +	if !isNotABS(name, i.dice.Logger) {
这个是什么意思（统一使用相对路径处理不行吗*（

2024-05-03 11:42 UTC, Xiangze-Li commented on dice/js_api.go
> +	return !os.IsNotExist(err)
例如：从外部复制来文件作为插件的静态资源，海豹可能不具有读取这个文件的权限。

2024-05-03 11:51 UTC, Xiangze-Li commented on dice/js_api.go
> +func (i *ExtInfo) FileWrite(name string, mod string, ctx string) error {
mod 参数在没有编辑器注释的情况下使用不便。

建议：分成两个函数 FileAppend 和 FileOverwrite

2024-05-03 11:51 UTC, Xiangze-Li commented on dice/js_api.go
> +		// use logger here
这些完全重复代码内容的注释可以去掉

2024-05-03 11:51 UTC, Xiangze-Li commented on dice/js_api.go
> +func ErrorLog(logger *zap.SugaredLogger) func(string) {
命名建议：ErrorLogFunc 以体现此函数并不真的执行日志，而是返回函数闭包

2024-05-04 04:59 UTC, Szzrain commented on dice/js_api.go
> +	if !isNotABS(name, i.dice.Logger) {
这里的判断逻辑是，将相对路径转换为绝对路径，然后根据前缀判断是否在限制的目录内，这样你就避免了使用相对路径进行判断时../这种情况导致的安全问题

2024-05-04 09:48 UTC, fy0 commented
思路上的一些问题：

首先，是群众说的那些安全性上的问题

第二个，即使要加入文件api
像是nodejs生态中已经存在很多成熟的文件api实现
如果要实现应该尽可能搞得跟他们相像，以免二次的学习成本
这里特殊需求是注入ext，那最前面创造一条不一样的api去注入，创建一个带闭包的环境
然后后面一直用这个环境，api可以完全参照成熟系统的经验

第三点，另外复杂的读写设计并不一定在实践中具有意义
就好像go有很多读写函数，文件流之类的
但是群众日常最常用的东西是 os.ReadFile
只有迫不得已才会真的用文件流去读，低于10mb的文件都懒得动脑子

思路的发散：
或者可以允许一个全功能的io模块，但前提是，用户手动打开这个选项。
比如说为goja写一个fs/promises（目前github上好像没有类似项目）。
不做任何限制 用户知晓危险后注入进去，这样插件编写可以直接用网上抄的nodejs的代码去操作。

2024-05-04 10:15 UTC, yichere commented
先 close ，等到学会 goga nodejs库时在去写（

2024-05-04 10:15 UTC, closed without merging