feat(js): 实现插件配置项有序展示
sealdice/sealdice-core pull request #802
Opened 2024-05-22 11:59 UTC by MintCider

解决 #772 

关联前端PR：https://github.com/sealdice/sealdice-ui/pull/195

## Disclaimer

不了解本项目的一般 contribution 流程，总之 PR 先放在这里，欢迎指正

2024-05-22 13:46 UTC, JustAnotherID commented
先听 lint 大爷怎么说（

2024-05-22 13:47 UTC, MintCider commented
> 先听 lint 大爷怎么说（

我记得我 clone 下来还没改呢 golint-ci 就不开心（x）我晚些看看

2024-05-22 13:57 UTC, Xiangze-Li reviewed
请参考

2024-05-22 13:57 UTC, Xiangze-Li commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
这样的话同一个配置项就在落盘的文件里被保存了两次。如果手动修改了其中一个，以哪一个为准呢？

或许可以把这个表示排序的数组改成 `[]string`，只保存 key 的顺序。

2024-05-22 14:02 UTC, MintCider commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
> 这样的话同一个配置项就在落盘的文件里被保存了两次

确实不好。

> 把这个表示排序的数组改成 `[]string`

这样的话前端可能改动比较大，我研究一下

2024-05-22 14:29 UTC, Xiangze-Li commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
考虑采用这样的设计：在接口不使用存储用的数据结构，而是在前端请求时临时将一个插件的配置排列成一个 `[]*ConfigItem` 传给前端。这样的话前端就直接拿到了正确顺序，遍历起来应该变化不大。

具体来说是 `api/api_bind.go` 的 `handleGetConfigs` 和 `handleSetConfigs`

2024-05-22 14:36 UTC, MintCider commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
hmmm 也就是以 `[]string` 记录配置项的顺序，然后把前后端现在的接口由 map 改成 list 么？

我觉得这样是好设计，但是不知道是否会违反你们现在对前后端 API 的规约。目前的实现是直接序列化整个 `Plugins` 结构体，而我没找到定义前后端接口的文件（x

2024-05-22 14:47 UTC, Xiangze-Li commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
通过接口传递的数据可能是以下的样子：

```json
{
  "some plugin name": {
    "pluginName": "some plugin name",
    "configs": [
      { "key": "X", ... } 
    ]
  }
}
```

2024-05-22 14:49 UTC, MintCider commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
WIP

```golang
// api/api_model.go

package api

import (
	"sealdice-core/dice"
)

type getConfigPluginConfig struct {
	PluginName string             `json:"pluginName"`
	Configs    []*dice.ConfigItem `json:"configs" jsbind:"configs"`
}

type getConfigResp map[string]*getConfigPluginConfig
```

2024-05-22 15:15 UTC, MintCider commented on dice/config.go
> +	OrderedConfigs []*ConfigItem `json:"orderedConfigs" jsbind:"orderedConfigs"`
可以看看现在的写法

2024-05-22 16:45 UTC, JustAnotherID requested changes

2024-05-22 16:45 UTC, JustAnotherID commented on api/api_model.go
> +type apiPluginConfig struct {
按目前仓库的惯例来说，这些结构体还是不要单独起个文件了，就近放在对应的方法前面就好。

2024-05-22 16:48 UTC, JustAnotherID requested changes

2024-05-22 16:48 UTC, JustAnotherID commented on dice/config.go
> +	newOrderedConfigKeys := make([]string, 0)
```suggestion
	newOrderedConfigKeys := make([]string, 0, len(plugin.OrderedConfigKeys))
```

2024-05-23 07:04 UTC, Szzrain approved these changes
LGTM

2024-05-23 07:16 UTC, Xiangze-Li commented
UI的PR修改完毕后我会一起合并

2024-05-23 07:40 UTC, merged