imp: 改进了详情信息的显示方式，同时st-1-1的行为进行兼容修正(来自ds的更新)
sealdice/sealdice-core pull request #846
Opened 2024-06-23 08:09 UTC by fy0

2024-06-23 13:01 UTC, Xiangze-Li commented on dice/config.go
> +	V2Compatible    int                `json:"v2Compatible"`    // 对v2的兼容描述，0代表兼容，1代表有if潜在不兼容，2代表不兼容
在什么地方引用了这个字段？

2024-06-23 14:07 UTC, fy0 commented on dice/rollvm_migrate.go
> +
啊，一开始打算把字数检查机制写到这里的，但是后来没有这样用。然而最后想了一下，果然还是应该写在这里

2024-06-23 14:07 UTC, fy0 commented on dice/config.go
> +	V2Compatible    int                `json:"v2Compatible"`    // 对v2的兼容描述，0代表兼容，1代表有if潜在不兼容，2代表不兼容
这是接下来要使用的妙妙字段

2024-06-23 14:13 UTC, Xiangze-Li commented on dice/config.go
> +	V2Compatible    int                `json:"v2Compatible"`    // 对v2的兼容描述，0代表兼容，1代表有if潜在不兼容，2代表不兼容
等到实际使用时再添加。将此字段在此时添加，到实际使用时容易使reviewer无法理解字段的来源。

2024-06-23 14:14 UTC, Xiangze-Li commented on dice/rollvm_migrate.go
> +
去掉或按你「最后想了一下」的写法实现

2024-06-27 17:06 UTC, JustAnotherID requested changes
群内 v20 预览版本出现对插件 api 行为的不兼容变更，当前的 master 最新代码与目前的正式版本均无此现象。
最小复现插件代码：
```js
if (!seal.ext.find("test-demo")) {
  const ext = seal.ext.new("test-demo", "JustAnotherID", "1.0.0");
  seal.ext.register(ext);
  ext.onCommandReceived = (ctx, msg, cmdArgs) => {
    if (cmdArgs.command === "r") {
      let [val, _] = seal.vars.intGet(ctx, "$t计算结果");
      seal.replyToSender(ctx, msg, `插件获取到的变量数据：${val}`);
    }
  };
}
```
旧行为：每次执行 `.r` 时能拿到上次执行的结果
新现象：永远只能拿到 0

2024-06-28 06:12 UTC, Xiangze-Li commented
反正已经堆积多个问题了，请你连这个一起修了吧

2024-06-28 21:15 UTC, Szzrain commented
#854

2024-07-01 05:14 UTC, Xiangze-Li commented
> 群内 v20 预览版本出现对插件 api 行为的不兼容变更，当前的 master 最新代码与目前的正式版本均无此现象。 最小复现插件代码：
> 
> ```js
> if (!seal.ext.find("test-demo")) {
>   const ext = seal.ext.new("test-demo", "JustAnotherID", "1.0.0");
>   seal.ext.register(ext);
>   ext.onCommandReceived = (ctx, msg, cmdArgs) => {
>     if (cmdArgs.command === "r") {
>       let [val, _] = seal.vars.intGet(ctx, "$t计算结果");
>       seal.replyToSender(ctx, msg, `插件获取到的变量数据：${val}`);
>     }
>   };
> }
> ```
> 
> 旧行为：每次执行 `.r` 时能拿到上次执行的结果 新现象：永远只能拿到 0

已单开 Issue #857 跟踪 @JustAnotherID

2024-07-02 00:20 UTC, Szzrain commented
> 群内 v20 预览版本出现对插件 api 行为的不兼容变更，当前的 master 最新代码与目前的正式版本均无此现象。 最小复现插件代码：
> 
> ```js
> if (!seal.ext.find("test-demo")) {
>   const ext = seal.ext.new("test-demo", "JustAnotherID", "1.0.0");
>   seal.ext.register(ext);
>   ext.onCommandReceived = (ctx, msg, cmdArgs) => {
>     if (cmdArgs.command === "r") {
>       let [val, _] = seal.vars.intGet(ctx, "$t计算结果");
>       seal.replyToSender(ctx, msg, `插件获取到的变量数据：${val}`);
>     }
>   };
> }
> ```
> 
> 旧行为：每次执行 `.r` 时能拿到上次执行的结果 新现象：永远只能拿到 0

should be fixed

2024-07-02 00:25 UTC, Szzrain commented
![image](https://github.com/sealdice/sealdice-core/assets/54656633/8b9a2c8b-4121-40ec-9bd4-241d81db7f0d)
经过测试后应当已经修复 #857

2024-07-02 00:50 UTC, Xiangze-Li commented on dice/rollvm_migrate.go
> +
我将另开 Issue 跟踪这一问题

2024-07-02 00:51 UTC, Xiangze-Li commented on dice/config.go
> +	V2Compatible    int                `json:"v2Compatible"`    // 对v2的兼容描述，0代表兼容，1代表有if潜在不兼容，2代表不兼容
见识过别的地方之后，我认为此处已经写得非常好了，不值得评论

2024-07-02 00:52 UTC, Xiangze-Li approved these changes
虽然还有问题，但是修复致命 bug 是主要的

2024-07-02 00:53 UTC, merged