fix: ri =d20这种语法不起效，以及.st技能相关问题
sealdice/sealdice-core pull request #905
Opened 2024-07-11 12:58 UTC by fy0

Fix #901 
Fix #903

2024-07-11 13:16 UTC, Xiangze-Li requested changes
基于实测效果，变化值的表示是有问题的。

这里表示成白值的变化（0→1）可能是较好的，如果不方便的话总值（8→9）也能接受

![image](https://github.com/sealdice/sealdice-core/assets/45380560/c08dc71f-6246-4644-8b6e-c75860e3cfba)

2024-07-12 06:06 UTC, Xiangze-Li commented
@MintCider 你的修改看起来并不直接依赖此处的修改，考虑单独开一个 PR，可以快速合并

2024-07-12 07:04 UTC, MintCider commented
主要是我不是很确定该向哪里 Merge，现在有 `master`，`dev`，`develop-1.5.0`

2024-07-12 07:06 UTC, Xiangze-Li commented
> 主要是我不是很确定该向哪里 Merge，现在有 `master`，`dev`，`develop-1.5.0`

你的修改是修复150版本重新DnD造成的bug，指向master

2024-07-15 17:49 UTC, fy0 commented
进行了调整
![image](https://github.com/user-attachments/assets/f565dee9-9a7b-4053-a274-98c892ff920f)

2024-07-15 23:18 UTC, Xiangze-Li approved these changes

2024-07-15 23:19 UTC, merged