feat: 添加 master jsclear 指令清除插件存储
sealdice/sealdice-core pull request #914
Opened 2024-07-15 04:32 UTC by oissevalt

- 添加 `func (d *Dice) ClearExtStorage(name string) error`，删除 `data/default/extensions/{name}/storage.db`
- 添加 master jsclear 命令，执行上面的函数，不可删除内置插件数据

2024-07-15 04:55 UTC, Xiangze-Li commented on dice/builtin_commands.go
> +				if err := ctx.Dice.ClearExtStorage(extName); err != nil {
在插件运行中这个文件可能会被当前进程占用或持续写入？

2024-07-15 14:48 UTC, oissevalt commented
我是 *Unix 系统，文件直接删也没提示的，而且 storage.db 写入时间短，我这里没法测试

2024-07-15 18:44 UTC, Szzrain requested changes
我比较反对往 `Dice` 里面添加新的方法，能否将其作为一个静态方法，然后传入 Dice 和对应的扩展名

2024-07-18 15:51 UTC, Szzrain approved these changes
LGTM

2024-07-18 16:15 UTC, merged