fix(dnd5e): 修正rc代骰，以及死亡豁免文案等问题
sealdice/sealdice-core pull request #918
Opened 2024-07-16 09:04 UTC by fy0

Fix #894

Fix #900

Fix #917

Fix #920
 
Close #893

修正死亡豁免表达式显示
修正seal.format对于dnd5e模板计算属性的错误显示
修正rc代骰问题
增加被察到模板

2024-07-16 09:10 UTC, Xiangze-Li commented on dice/ext_fun.go
> +
xx 是什么? 怎么又要打印出来?

2024-07-16 09:25 UTC, Xiangze-Li requested changes

2024-07-16 09:25 UTC, Xiangze-Li commented on dice/ext_dnd5e.go
如下图，计算属性的 st show 仍不正确

![0bea2c094da0f5b75a8d6aa68f93d60b](https://github.com/user-attachments/assets/432848cb-893a-4bf4-88f1-4877a82b7ff8)

2024-07-16 09:25 UTC, Xiangze-Li commented on dice/ext_dnd5e.go
如下图，死亡豁免优势或劣势时未有体现

![1986bf50f77441b129388217e8a17f89](https://github.com/user-attachments/assets/df516ad1-432d-4619-b95e-3d2bf40ea86f)

2024-07-16 09:31 UTC, Xiangze-Li commented
As of [39ce14a](https://github.com/sealdice/sealdice-core/pull/918/commits/39ce14ab7adf3eeb5780f74040b1d68100f17978):

- #917 verified
- #893 verified

2024-07-16 11:01 UTC, fy0 commented on dice/ext_dnd5e.go
st show不在本次修复范围内

2024-07-16 11:02 UTC, fy0 commented on dice/ext_dnd5e.go
ok

2024-07-16 11:12 UTC, Xiangze-Li commented on dice/ext_dnd5e.go
#919

2024-07-17 02:20 UTC, Xiangze-Li commented
#920 是否也由此 PR 的修改解决？需要分析原问题 @fy0

2024-07-17 07:33 UTC, fy0 commented on dice/ext_dnd5e.go
<王五>的死亡豁免检定: [D20优势={15 | 2}]=15 伤势暂时得到控制！死亡豁免成功+1
累计获得了3次死亡豁免检定成功，伤势稳定了！
当前情况: 成功3 失败1

2024-07-17 07:34 UTC, fy0 commented
> #920 是否也由此 PR 的修改解决？需要分析原问题 @fy0

理论能够解决，底层原因是getCtxProxyFirst中对ctx进行复制时带入了旧的vm

2024-07-17 07:49 UTC, Xiangze-Li commented
As of [f694959](https://github.com/sealdice/sealdice-core/pull/918/commits/f694959854580b7c3355a7bc82e72ebd42951ef4):

- #894 验证
- #900 #920 认为是相同问题，需要验证是否已解决

2024-07-17 10:35 UTC, MX-fox commented
> As of [f694959](https://github.com/sealdice/sealdice-core/pull/918/commits/f694959854580b7c3355a7bc82e72ebd42951ef4):
> 
> * [[150 Bug](DnD): 死亡豁免(ds) 指令中骰子面数显示丢失 #894](https://github.com/sealdice/sealdice-core/issues/894) 验证
> * [[150 Bug](DnD): rc指令代骰读取数据错误 #900](https://github.com/sealdice/sealdice-core/issues/900) [[150 Bug]: js插件若对指令开启代骰，则seal.format()获取到的值为被艾特者而非触发者的变量值 #920](https://github.com/sealdice/sealdice-core/issues/920) 认为是相同问题，需要验证是否已解决

* [[150 Bug](DnD): rc指令代骰读取数据错误 #900](https://github.com/sealdice/sealdice-core/issues/900) 验证
* [[150 Bug]: js插件若对指令开启代骰，则seal.format()获取到的值为被艾特者而非触发者的变量值 #920](https://github.com/sealdice/sealdice-core/issues/920) 验证

2024-07-18 01:45 UTC, Xiangze-Li approved these changes
看求不懂，反正效果差不多

2024-07-18 01:47 UTC, merged